# -*- coding: utf-8 -*-
"""Set_Seed_Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBpWHcj80KthleXleNvE_FnScNtm-TEr

#This is a practice on constant, variable, random tensors and shuffling tensors

#Creating A Constant Tensor :

Importing Required Libraries
"""

import tensorflow as tf
import random as ra
print('''Rank v/s Tensor :
Scalar -> Rank = 0
Vector -> Rank = 1
Matrix -> Rank = 2
Tensor -> Rank = 3\n
''')
print("Constant Tensors :")
ct1 = tf.constant(1)
ct2 = tf.constant([1, 2])
ct3 = tf.constant([
    [1, 2],
    [3, 4]
])
ct4 = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(f"""Scalar :
{ct1}
Vector :
{ct2}
Matrix :
{ct3}
Tensor :
{ct4}""")

"""#We Can't Change the values of tf.constant which will raise attribute error"""

try:
  ct2[0].assign(29)
except Exception as e:
  print("Exception Occured : ", e)

"""#Dimensions of a tensor can be found using .ndim"""

print("The Deminetions of the Tensors are : ")
print(f"""Scalar = {ct1.ndim}
Vector = {ct2.ndim}
Matrix = {ct3.ndim}
Tensor = {ct4.ndim}""")

"""#WE can know the shape of a tensosr using .shape"""

print("The Shapes of the tensor are : ")
print(f"""Scalar = {ct1.shape}
Vector = {ct2.shape}
Matrix = {ct3.shape}
Tensor = {ct4.shape}""")

"""#We can specify the datatype and size of each element in a tensor using dtype = tf.int32 and so on..."""

print("Tensors on required size and data type : (Example used here is tf.float64)")
ct1 = tf.constant([1, 2, 3], dtype = tf.float64)
print(f"""Shape = {ct1.shape}
Dimensions = {ct1.ndim}""")

"""#The same can be done using tf.Variable() which is a class and all the operations performed on the tf.constant performed can be here"""

print("Tensorflow Variable's : ")
vt1 = tf.Variable(23)
vt2 = tf.Variable([1, 2])
vt3 = tf.Variable([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
vt4 = tf.Variable([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    [
        [9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]
    ]
])
vt1, vt2, vt3, vt4

"""#Assigning the values the tf.variable usign .assign"""

vt2[0].assign(29)
vt2[1].assign(23)
vt2

"""#Creatng Random Tensors using tf.random.Generator.from_seed(x)"""

# rt1 = tf.random.Generator.from_seed(42)
tf.random.Generator.from_seed(42)  #Here All the random values are different
tf1 = tf.random.uniform(shape = (2, 2),)  #tf.random.Generator.from_seed(42) creates a new random number generator with a specific seed (42). This generator is then used to generate random numbers with the tf.random.uniform function.
print(tf1)

"""#Another Way of geberating random tensors but not everytime"""

tf.random.set_seed(42)  #By setting seed value the random value will be same
tf1 = tf.random.uniform(seed = 49, shape = (2, 2))  #tf.random.set_seed(42) sets the global seed for the TensorFlow random number generator. This seed affects all subsequent random operations, including the tf.random.uniform call.
print(tf1)

"""#Notes

Generator vs. Global Seed:

In Code 1, tf.random.Generator.from_seed(42) creates a new random number generator with a specific seed (42). This generator is then used to generate random numbers with the tf.random.uniform function.
In Code 2, tf.random.set_seed(42) sets the global seed for the TensorFlow random number generator. This seed affects all subsequent random operations, including the tf.random.uniform call.
Seed for tf.random.uniform:

In Code 1, the seed specified in from_seed(42) is used to initialize the generator, but it doesn't directly affect the tf.random.uniform call. The tf.random.uniform call doesn't have an explicit seed argument.
In Code 2, the seed is set globally with tf.random.set_seed(42), and then a specific seed (49) is provided to the tf.random.uniform call using the seed argument.
Resulting Random Numbers:

Due to the differences in how seeds are set and used, the random numbers generated by tf.random.uniform in these two codes may not be the same even though both use seeds. The specific values of the generated numbers depend on the TensorFlow version and the underlying random number generation implementation.
In summary, while both codes involve setting seeds for random number generation, the first one creates a specific generator with a seed, and the second one sets a global seed for TensorFlow and also provides a seed for the specific tf.random.uniform call. The specific behavior and resulting random numbers may vary based on the TensorFlow version and random number generation implementation.

#Shuffling Tensors
"""

tf.random.set_seed(23)
rTensor = tf.random.uniform(shape = (2, 2))
#Before Shuffling
print(rTensor)
#After Shuffling
shuffledTensor = tf.random.shuffle(rTensor)
print(shuffledTensor)     #It only Shuffles along one dimension

"""#To Check if GPU is Available"""

print(tf.config.list_physical_devices('GPU'))